#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

sudo touch /var/run/bestscript.pid
sudo bash -c "echo $$ > /var/run/bestscript.pid"

trap interrup2 SIGINT
trap interrup1 SIGTERM
trap interrup3 SIGQUIT

interrup3()
{
    sudo rm /var/run/bestscript.pid
    exit $?
}

interrup2()
{
    echo "Y U no love me?!"
}

interrup1()
{
    echo "I hate the kill command"
    sudo rm /var/run/bestscript.pid
    exit $?
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
